#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

transaction:
  defaultHandler: org.seedstack.jdbc.internal.JdbcTransactionHandler
jdbc:
  defaultDatasource: datasource1
  datasources:
    datasource1:
      provider: org.seedstack.jdbc.internal.datasource.PlainDataSourceProvider
      url: jdbc:hsqldb:mem:testdb1
    datasource2:
      provider: org.seedstack.jdbc.internal.datasource.HikariDataSourceProvider
      url: jdbc:hsqldb:mem:testdb2
    datasource3:
      provider: org.seedstack.jdbc.internal.datasource.DbcpDataSourceProvider
      url: jdbc:hsqldb:mem:testdb3
    datasource4:
      provider: org.seedstack.jdbc.internal.datasource.C3p0DataSourceProvider
      url: jdbc:hsqldb:mem:testdb4
